In [76]:
import torch
import numpy as np
from torch.autograd import Variable

In [3]:
arr=[[1,2],[3,4]]
print(arr)

[[1, 2], [3, 4]]


In [4]:
np.array(arr)

array([[1, 2],
       [3, 4]])

In [5]:
#torch
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

In [7]:
#numpy
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [8]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [9]:
#random numbers
np.random.rand(2,2)

array([[0.93667896, 0.98720218],
       [0.85948325, 0.55438151]])

In [10]:
torch.rand(2,2)

tensor([[0.2238, 0.1521],
        [0.0106, 0.0241]])

In [11]:
#Seeds for reproducibility
np.random.seed(123)
np.random.rand(2,2)

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477]])

In [14]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [15]:
#Torch Seed
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [16]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [17]:
torch.rand(2,2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

In [18]:
#gpu
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

#### Torch to Numpy Bridge

In [19]:
np_array=np.ones((2,2))

In [20]:
print(np_array)

[[1. 1.]
 [1. 1.]]


In [21]:
print(type(np_array))

<class 'numpy.ndarray'>


In [22]:
#Convert to Torch Tensor
torch_tensor=torch.from_numpy(np_array)

In [23]:
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [24]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [26]:
np_array_new=np.ones((2,2),dtype=np.int8)
torch.from_numpy(np_array_new)

TypeError: can't convert np.ndarray of type numpy.int8. The only supported types are: double, float, float16, int64, int32, and uint8.

In [27]:
np_array_new=np.ones((2,2),dtype=np.int32)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [28]:
np_array_new=np.ones((2,2),dtype=np.uint8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)

In [29]:
np_array_new=np.ones((2,2),dtype=np.int64)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]])

In [30]:
np_array_new=np.ones((2,2),dtype=np.float32)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]])

In [31]:
np_array_new=np.ones((2,2),dtype=np.double)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

#### Torch to Numpy

In [32]:
torch_tensor=torch.ones(2,2)

In [33]:
type(torch_tensor)

torch.Tensor

In [35]:
torch_to_numpy=torch_tensor.numpy()

In [36]:
type(torch_to_numpy)

numpy.ndarray

### CPU VS GPU toggling

In [37]:
tensor_cpu=torch.ones(2,2)

In [38]:
#CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [39]:
#GPU to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

### Tensor Operations

In [40]:
#Resizing Tensor
a=torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [42]:
print(a.size())

torch.Size([2, 2])


In [46]:
a=a.view(4)

In [47]:
a.size()

torch.Size([4])

In [48]:
#Element-wise addition
a=torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [49]:
b=torch.ones(2,2)
print(b)

tensor([[1., 1.],
        [1., 1.]])


In [50]:
c=torch.add(a,b)
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [52]:
c=a+b
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [54]:
#In place addition
print('Old C tensor')
print(c)

c.add_(a)
print('-'*60)
print('New c tensor')
print(c)

Old C tensor
tensor([[2., 2.],
        [2., 2.]])
------------------------------------------------------------
New c tensor
tensor([[3., 3.],
        [3., 3.]])


In [55]:
#Element wise subtraction
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [56]:
print(b)

tensor([[1., 1.],
        [1., 1.]])


In [57]:
a-b

tensor([[0., 0.],
        [0., 0.]])

In [58]:
#In place subtraction
a.sub_(b)
print(a)

tensor([[0., 0.],
        [0., 0.]])


In [59]:
#Element wise Multiplication
a=torch.ones(2,2)
print(a)
b=torch.zeros(2,2)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [60]:
print(torch.mul(a,b))

tensor([[0., 0.],
        [0., 0.]])


In [62]:
print('old a')
print(a)

a.mul_(b)

print('new a')
print(a)

old a
tensor([[1., 1.],
        [1., 1.]])
new a
tensor([[0., 0.],
        [0., 0.]])


In [63]:
#Element wise Division
a=torch.ones(2,2)
b=torch.zeros(2,2)

In [64]:
b/a

tensor([[0., 0.],
        [0., 0.]])

In [65]:
#inplace division
b.div_(a)

tensor([[0., 0.],
        [0., 0.]])

### Tensor Mean

In [66]:
a=torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.size()

torch.Size([10])

In [67]:
a.mean(dim=0)

tensor(5.5000)

In [68]:
a.mean(dim=1)

RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [70]:
a=torch.Tensor([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
a.size()

torch.Size([2, 10])

In [71]:
#column mean
a.mean(dim=1)

tensor([5.5000, 5.5000])

In [72]:
#row mean
a.mean(dim=0)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [74]:
#std deviation
a=torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.std(dim=0)

tensor(3.0277)

### Variables

In [77]:

a=Variable(torch.ones(2,2),requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [78]:
#Behave similarly to tensors ex addition
b=Variable(torch.ones(2,2),requires_grad=True)
print(a+b)
print(torch.add(a,b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [79]:
print(a*b)
print(torch.mul(a,b))

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


### Gradients

In [98]:
x=Variable(torch.ones(2),requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

In [99]:
y=5*(x+1)**2
y

tensor([20., 20.], grad_fn=<MulBackward0>)

In [100]:
o=(1/2)*torch.sum(y)
print(o)

tensor(20., grad_fn=<MulBackward0>)


In [84]:
o.backward()

In [85]:
x.grad

tensor([10., 10.])

In [101]:
#backward in detail something wrong here
o.backward(torch.FloatTensor([1.0,1.0]))
print(x.grad)

tensor([20., 20.])
